### ISSUE TITLE
Unit Test fail due to invalid 'user.email'

### ISSUE THREAD

**Issue by lowell80** [Kintyre/ksconf#19]
Appears that `user.email` config isn't being set/guessed correctly on my Windows 10 test VM.  This is not an issue with Appveyor because we explicitly call `git config` to set this up.  Unit tests should handle this internally to avoid such external dependencies.

    fatal: unable to auto-detect email address (got 'Lowell@WIN10E-LOWELL.(none)')

Unit test stack trace:

```
======================================================================
ERROR: test_modsec_install_upgrade (test_cli.CliKsconfUnarchiveTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Lowell\Sandbox\ksconf\tests\test_cli.py", line 786, in test_modsec_install_upgrade
    self._modsec01_install_11(twd)
  File "C:\Users\Lowell\Sandbox\ksconf\tests\test_cli.py", line 801, in _modsec01_install_11
    twd.git("commit", "-m", "Add custom file.")
  File "C:\Users\Lowell\Sandbox\ksconf\tests\test_cli.py", line 129, in git
    raise RuntimeError("Failed git command (return code {0})".format(o.returncode))
RuntimeError: Failed git command (return code 128)

```

Shell output:

    Git command 'git commit -m Add custom file.' failed with exit code 128

    *** Please tell me who you are.

    Run

      git config --global user.email "you@example.com"
      git config --global user.name "Your Name"

**Comment by lowell80** [comment]
Fixed as of v0.5.0 (ebfcf0e888d49002)
