### ISSUE TITLE
ksconf upgrade from 0.9.2 to 0.11.7 (as a splunk app)

### ISSUE THREAD

**Issue by yohonet** [Kintyre/ksconf#99]
# The problem

ksconf is not working and not even able to display its version number. Is there any missing python package in Splunk to support 0.11.7 ?

## Environment

* Ksconf version:  0.11.7
* OS & version used: RHEL 7.9
* Python version: Python 3.7.11, embedded with Splunk (version 9.0.4)
* Installed via: Splunk app

## Details

```
$ ksconf --version
Traceback (most recent call last):
  File "/opt/splunk/bin/ksconf", line 10, in <module>
    from ksconf.__main__ import cli
  File "/opt/splunk/etc/apps/ksconf/bin/lib/ksconf/__main__.py", line 39, in <module>
    from ksconf.cli import cli
  File "/opt/splunk/etc/apps/ksconf/bin/lib/ksconf/cli.py", line 26, in <module>
    from ksconf.commands import DescriptionHelpFormatterPreserveLayout, get_all_ksconf_cmds
  File "/opt/splunk/etc/apps/ksconf/bin/lib/ksconf/commands/__init__.py", line 22, in <module>
    from ksconf.hook import plugin_manager
  File "/opt/splunk/etc/apps/ksconf/bin/lib/ksconf/hook.py", line 4, in <module>
    from pluggy import HookimplMarker, PluginManager
  File "/opt/splunk/etc/apps/ksconf/bin/lib/pluggy/__init__.py", line 23, in <module>
    from ._manager import PluginManager, PluginValidationError
  File "/opt/splunk/etc/apps/ksconf/bin/lib/pluggy/_manager.py", line 4, in <module>
    from importlib_metadata import metadata
ModuleNotFoundError: No module named 'importlib_metadata'
```

**Comment by lowell80** [comment]
Please give version 0.11.9 a try.   This should resolve all the Splunk app packaging specific errors you were encountering.

**Comment by yohonet** [comment]
Confirmed, package 0.11.9 fix it. Thanks !

```shell
$ ksconf --version
.-..-. .--.                  .--.
: :' ;: .--'                  : .-'
:   ' `. `.  .--.  .--. ,-.,-.: `;
: :.`. _`, :'  ..'' .; :: ,. :: :
:_;:_;`.__.'`.__.'`.__.':_;:_;:_;

ksconf 0.11.9  (Build 1194)
Python: 3.7.11  (/opt/splunk/bin/python3)
Git SHA1 73922917 committed on 2023-09-26
Installed at: /opt/splunk/etc/apps/ksconf/bin/lib/ksconf
Platform:  #1 SMP Thu May 18 11:23:40 UTC 2023
Git support:  (/usr/bin/git) git version 1.8.3.1
Written by Lowell Alleman <lowell@kintyre.co>.
Copyright (c) 2019 Kintyre Solutions, Inc, all rights reserved.
Licensed under Apache Public License v2

  kintyre  (splunk-conf)

    Commands:
      check           (stable)    OK
      combine         (beta)      OK
      diff            (stable)    OK
      filter          (alpha)     OK
      merge           (stable)    OK
      minimize        (beta)      OK
      package         (beta)      OK
      promote         (beta)      OK
      rest-export     (beta)      OK
      rest-publish    (alpha)     Missing 3rd party module:  _ssl
      snapshot        (alpha)     OK
      sort            (stable)    OK
      unarchive       (beta)      OK
      xml-format      (alpha)     OK   (lxml 4.6.5)
```
